### ISSUE TITLE
Initial example from documentation yields error

### ISSUE THREAD

**Issue by zyrolasting** [dbenoit17/dynamic-ffi#25]
Going by https://docs.racket-lang.org/dynamic-ffi/index.html#%28part._.Defining_.F.F.Is%29

I am using Fedora 30. I ran `    sudo dnf install "@development tools" racket llvm-devel clang-devel` as instructed.

I then pasted the example from the docs:

```
#lang racket/base

(require dynamic-ffi/unsafe) 

(define-dynamic-ffi libc
  (dynamic-ffi-lib "libc" "6")
  "/usr/include/stdio.h")

(libc 'printf "hello world")
```

Running this from the shell using `racket` raises the following:

```
void only allowed as pointer or function return
  context...:
   /home/sage/.racket/7.4/pkgs/dynamic-ffi/ffi.rkt:57:0: make-ffi-array
   /home/sage/.racket/7.4/pkgs/dynamic-ffi/ffi.rkt:120:4: for-loop
   /home/sage/.racket/7.4/pkgs/dynamic-ffi/ffi.rkt:112:0: build-ffi-obj-map
   "/home/sage/Code/dyn.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
```

What was my error here?

**Comment by zyrolasting** [comment]
(I have not verified this, but does the error imply a signature of form `void foo(void)`?)

**Comment by dbenoit17** [comment]
Yes, exactly.  I think my initial thought may have been to reject something of the form `void foo(void bar)`, which is itself redundant because clang should reject it before it gets to racket.  It looks like a change to either libc or the clang parser libraries has exposed this mistake of rejecting such a declaration.

This commit should fix it. https://github.com/dbenoit17/dynamic-ffi/commit/8b8001931b77a61ab5d8dddfa58a15b5ccdeee95#diff-ac51c09b9e2376fe5e35cd992ad4e6d6L99-R99

Thank you for reporting this!

**Comment by zyrolasting** [comment]
And thank you for jumping on it!
